server:
  error:
    include-message: always
  port: 8080

spring:
  thymeleaf:
    enabled: true
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/course-work
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

application:
  security:
    jwt:
      secret-key: 316c0a2a82b1cda7e48bfd32737b7d38043c574be0cbf92180f7a57fb35e5b40
      expiration: 300_000
      refresh-token:
        expiration: 86_400_000

cloud:
  aws:
    region: eu-north-1
    s3:
      buckets:
        users: course-work-users
        fishCatches: course-work-fish-catches
        locations: course-work-locations
      max-file-size: 7_340_032

app:
  constants:
    posts:
      likes-page-size: 20
      comment-page-size: 20
    users:
      likes-page-size: 20

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  file:
    name: logs/app.log